devices:
 samsung:
  caps:
   deviceName: "Samsung"
   platformName: "Android"
   version: "6.0.1"
   app: "C:/AutomacaoTreinamentos/INLabs/Mobile/Teste_Appium/AppiumTest/features/support/ApkProvaCarros.apk"
   appPackage: "br.com.ftec.ailton.cadastrodecarrosweb"
   appActivity: "br.com.ftec.ailton.cadastrodecarrosweb.MainActivity"
   newCommandTimeout: "3600"
   port: 4724
   appium_port: 4724
   appium_lib: { wait: 20, debug: false}
